name: Continuous Deployment

on:
  push:
    tags:
      - 'production'
  workflow_dispatch:

jobs:
  app:
    name: Deploy application
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up docker context
        uses: amirmarmul/docker-context-ssh-action@v2
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-private-key: ${{ secrets.SSH_KEY }}
          context-name: cloud
          context-use: true

      - name: Set environment
        run: |
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}" >> $GITHUB_ENV

          echo "MAILER_SENDER=${{ secrets.MAILER_SENDER }}" >> $GITHUB_ENV

          echo "APP_HOST=${{ secrets.APP_HOST }}" >> $GITHUB_ENV
      - name: Deploy application
        env:
          GHCR_USER: ${{ secrets.GHCR_TOKEN }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          COMPOSE_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          cd ops
          docker-compose pull
          docker-compose up migration
          docker-compose up --detach app
